# GKE ingress: global static IP, Cloud DNS A record, and Helm values for GLB + ManagedCertificate.

variable "domain" {
  description = "Public hostname for Ortelius (frontend Ingress + ManagedCertificate)"
  type        = string
}

variable "dns_managed_zone" {
  description = "Cloud DNS managed zone name (Console → Network Services → Cloud DNS). Empty skips Terraform DNS."
  type        = string
  default     = ""
}

variable "static_ip_name" {
  description = "GCP global address name; must match frontend.ingress.staticIP in Helm values"
  type        = string
  default     = "ortelius-gke-ip"
}

resource "google_compute_global_address" "app" {
  name    = var.static_ip_name
  project = var.project_id
}

data "google_dns_managed_zone" "app" {
  count = var.dns_managed_zone != "" ? 1 : 0

  name    = var.dns_managed_zone
  project = var.project_id
}

resource "google_dns_record_set" "app" {
  count = var.dns_managed_zone != "" ? 1 : 0

  project      = var.project_id
  managed_zone = data.google_dns_managed_zone.app[0].name
  name         = "${var.domain}."
  type         = "A"
  ttl          = 300
  rrdatas      = [google_compute_global_address.app.address]
}

resource "local_file" "ortelius_values" {
  filename = "${path.module}/../../clusters/gke/ortelius/values.yaml"
  content  = <<-YAML
    # Auto-generated by Terraform (terraform/gke/ingress.tf) — do not edit by hand.
    # Re-apply Terraform after changing domain or static_ip_name.
    # Secrets: clusters/gke/ortelius/secrets.enc.yaml

    frontend:
      graphqlEndpoint: "https://${var.domain}/api/v1/graphql"
      restapiEndpoint: "https://${var.domain}/api/v1"
      ingress:
        enabled: true
        type: glb
        host: ${var.domain}
        staticIP: ${var.static_ip_name}

    ortelius:
      ingress:
        type: glb
      rbac_repo: "https://github.com/${var.github_org}/pdvd-rbac.git"
      apiBaseUrl: "https://${var.domain}"
      baseUrl: "https://${var.domain}"
      github:
        appName: ortelius
        org: ${var.github_org}
      smtp:
        enabled: true
        host: "smtp.gmail.com"
        port: "587"
        fromEmail: "noreply@${replace(var.domain, "/^[^.]+\\./", "")}"
        fromName: "Ortelius"

    arangodb:
      cloudProvider: gke
  YAML
}

output "domain" {
  description = "Ortelius public URL hostname"
  value       = var.domain
}

output "ortelius_url" {
  description = "Ortelius UI base URL"
  value       = "https://${var.domain}"
}

output "static_ip" {
  description = "Global static IP for GCE Ingress (A record target)"
  value       = google_compute_global_address.app.address
}

output "static_ip_name" {
  description = "GCP global address resource name (frontend.ingress.staticIP)"
  value       = google_compute_global_address.app.name
}

output "dns_record" {
  description = "Cloud DNS A record created by Terraform (empty if dns_managed_zone unset)"
  value       = var.dns_managed_zone != "" ? "${var.domain} -> ${google_compute_global_address.app.address}" : "DNS not managed by Terraform — point ${var.domain} A record to ${google_compute_global_address.app.address}"
}
